##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [4.7.0-B52] date: [Wed Apr 08 23:52:20 CST 2026] 
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = helloworld


######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -O0


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

# Cross-platform directory removal command
ifeq ($(OS),Windows_NT)
RM_DIR = cmd /C if exist "$(BUILD_DIR)" rmdir /S /Q "$(BUILD_DIR)"
else
RM_DIR = rm -fR $(BUILD_DIR)
endif

######################################
# source
######################################
# C sources
C_SOURCES =  \
Core/Src/main.c \
Core/Src/gpio.c \
Core/Src/stm32f4xx_it.c \
Core/Src/stm32f4xx_hal_msp.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.c \
Core/Src/system_stm32f4xx.c \
Core/Src/sysmem.c \
Core/Src/syscalls.c \
Core/Src/usart.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_uart.c \
Core/Src/freertos.c \
Core/Src/stm32f4xx_hal_timebase_tim.c \
Middlewares/Third_Party/FreeRTOS/Source/croutine.c \
Middlewares/Third_Party/FreeRTOS/Source/event_groups.c \
Middlewares/Third_Party/FreeRTOS/Source/list.c \
Middlewares/Third_Party/FreeRTOS/Source/queue.c \
Middlewares/Third_Party/FreeRTOS/Source/stream_buffer.c \
Middlewares/Third_Party/FreeRTOS/Source/tasks.c \
Middlewares/Third_Party/FreeRTOS/Source/timers.c \
Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/cmsis_os2.c \
Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang/heap_4.c \
Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F/port.c \
Middlewares/Systemview/src/SEGGER_RTT.c \
Middlewares/Systemview/src/SEGGER_RTT_printf.c \
Middlewares/EasyLogger/port/elog_port.c \
Middlewares/EasyLogger/src/elog.c \
Middlewares/EasyLogger/src/elog_async.c \
Middlewares/EasyLogger/src/elog_buf.c \
Middlewares/EasyLogger/src/elog_utils.c \
Debug/src/Debug.c

# ASM sources
ASM_SOURCES =  \
startup_stm32f411xe.s


#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
NM = $(GCC_PATH)/$(PREFIX)nm
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
NM = $(PREFIX)nm
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m4

# fpu
FPU = -mfpu=fpv4-sp-d16

# float-abi
FLOAT-ABI = -mfloat-abi=hard

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DUSE_HAL_DRIVER \
-DSTM32F411xE


# AS includes
AS_INCLUDES = 

# C includes
C_INCLUDES =  \
-ICore/Inc \
-IDrivers/STM32F4xx_HAL_Driver/Inc \
-IDrivers/STM32F4xx_HAL_Driver/Inc/Legacy \
-IDrivers/CMSIS/Device/ST/STM32F4xx/Include \
-IDrivers/CMSIS/Include \
-IMiddlewares/Third_Party/FreeRTOS/Source/include \
-IMiddlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 \
-IMiddlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F \
-IMiddlewares/Systemview/inc \
-IMiddlewares/EasyLogger/inc \
-IDebug/inc


# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS += $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = STM32F411XX_FLASH.ld

# MCU memory size (STM32F411xE)
FLASH_SIZE_BYTES = 524288
RAM_SIZE_BYTES = 131072

# libraries
LIBS = -lc -lm -lnosys 
LIBDIR = 
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin mem-report


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR):
	mkdir $@		

#######################################
# memory report
#######################################
ifeq ($(OS),Windows_NT)
mem-report: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin
	@powershell -NoProfile -Command "$$line = & '$(SZ)' '$(BUILD_DIR)/$(TARGET).elf' | Select-Object -Last 1; $$parts = $$line -split '\s+' | Where-Object { $$_ -ne '' }; $$text = [int]$$parts[0]; $$data = [int]$$parts[1]; $$bss = [int]$$parts[2]; $$flash = $$text + $$data; $$ram = $$data + $$bss; $$flashPct = [math]::Round(($$flash * 100.0) / $(FLASH_SIZE_BYTES), 2); $$ramPct = [math]::Round(($$ram * 100.0) / $(RAM_SIZE_BYTES), 2); Write-Host '=== Memory Usage Summary ==='; Write-Host ('FLASH used: {0} / $(FLASH_SIZE_BYTES) bytes ({1} pct)' -f $$flash, $$flashPct); Write-Host ('RAM used  : {0} / $(RAM_SIZE_BYTES) bytes ({1} pct)' -f $$ram, $$ramPct)"
	@powershell -NoProfile -Command "Write-Host ''; Write-Host '=== Section Breakdown ==='"
	@$(SZ) -A $(BUILD_DIR)/$(TARGET).elf
	@powershell -NoProfile -Command "Write-Host ''; Write-Host '=== Top 20 Symbols By Size ==='"
	@powershell -NoProfile -Command "& '$(NM)' -S --size-sort '$(BUILD_DIR)/$(TARGET).elf' | Select-Object -Last 20"
else
mem-report: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin
	@echo "=== Memory Usage Summary ==="
	@flash=`$(SZ) $(BUILD_DIR)/$(TARGET).elf | awk 'NR==2 {print $$1 + $$2}'`; \
	ram=`$(SZ) $(BUILD_DIR)/$(TARGET).elf | awk 'NR==2 {print $$2 + $$3}'`; \
	flash_pct=`awk 'BEGIN {printf "%.2f", ('$$flash' * 100.0) / $(FLASH_SIZE_BYTES)}'`; \
	ram_pct=`awk 'BEGIN {printf "%.2f", ('$$ram' * 100.0) / $(RAM_SIZE_BYTES)}'`; \
	echo "FLASH used: $$flash / $(FLASH_SIZE_BYTES) bytes ($$flash_pct%)"; \
	echo "RAM used  : $$ram / $(RAM_SIZE_BYTES) bytes ($$ram_pct%)"
	@echo
	@echo "=== Section Breakdown ==="
	@$(SZ) -A $(BUILD_DIR)/$(TARGET).elf
	@echo
	@echo "=== Top 20 Symbols By Size ==="
	@$(NM) -S --size-sort $(BUILD_DIR)/$(TARGET).elf | tail -n 20
endif

#######################################
# clean up
#######################################
clean:
	-$(RM_DIR)

.PHONY: all clean mem-report
  
#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***
