##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [4.7.0-B52] date: [Fri Apr 24 17:53:41 CST 2026] 
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = helloworld


######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -O0


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build
BUILD_LOG = $(BUILD_DIR)/build.log

# Cross-platform directory removal command
ifeq ($(OS),Windows_NT)
RM_DIR = cmd /C if exist "$(BUILD_DIR)" rmdir /S /Q "$(BUILD_DIR)"
else
RM_DIR = rm -fR $(BUILD_DIR)
endif

######################################
# source
######################################
C_SOURCES = \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_uart.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.c \
Middlewares/Third_Party/FreeRTOS/Source/croutine.c \
Middlewares/Third_Party/FreeRTOS/Source/event_groups.c \
Middlewares/Third_Party/FreeRTOS/Source/list.c \
Middlewares/Third_Party/FreeRTOS/Source/queue.c \
Middlewares/Third_Party/FreeRTOS/Source/stream_buffer.c \
Middlewares/Third_Party/FreeRTOS/Source/tasks.c \
Middlewares/Third_Party/FreeRTOS/Source/timers.c \
Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/cmsis_os2.c \
Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang/heap_4.c \
Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F/port.c \
Core/Src/main.c \
Core/Src/freertos.c \
Core/Src/system_stm32f4xx.c \
Core/Src/sysmem.c \
Core/Src/syscalls.c \
Core/Src/stm32f4xx_it.c \
Core/Src/stm32f4xx_hal_msp.c \
Core/Src/stm32f4xx_hal_timebase_tim.c \
Core/Src/gpio.c \
Core/Src/dma.c \
Core/Src/tim.c \
Core/Src/usart.c \
Core/Src/i2c.c \
Core/Src/iic_hal.c \
Core/Src/spi.c \
02_OS_Platform/OS_Implementation/src/os_impl_heap.c \
02_OS_Platform/OS_Implementation/src/os_impl_mutex.c \
02_OS_Platform/OS_Implementation/src/os_impl_queue.c \
02_OS_Platform/OS_Implementation/src/os_impl_sema.c \
02_OS_Platform/OS_Implementation/src/os_impl_task.c \
02_OS_Platform/OS_Implementation/src/os_impl_timer.c \
02_OS_Platform/OS_Implementation/src/os_impl_event_group.c \
02_OS_Platform/OS_Implementation/src/os_impl_notify.c \
02_OS_Platform/OS_Wrapper/src/osal_heap.c \
02_OS_Platform/OS_Wrapper/src/osal_mutex.c \
02_OS_Platform/OS_Wrapper/src/osal_notify.c \
02_OS_Platform/OS_Wrapper/src/osal_queue.c \
02_OS_Platform/OS_Wrapper/src/osal_sema.c \
02_OS_Platform/OS_Wrapper/src/osal_task.c \
02_OS_Platform/OS_Wrapper/src/osal_timer.c \
02_OS_Platform/OS_Wrapper/src/osal_event_group.c \
04_Debug_Tool/Systemview/src/SEGGER_RTT.c \
04_Debug_Tool/Systemview/src/SEGGER_RTT_printf.c \
04_Debug_Tool/Systemview/src/SEGGER_SYSVIEW.c \
04_Debug_Tool/Systemview/src/SEGGER_SYSVIEW_FreeRTOS.c \
04_Debug_Tool/Systemview/src/SEGGER_SYSVIEW_Config_FreeRTOS.c \
04_Debug_Tool/Debug_Log/src/Debug.c \
04_Debug_Tool/SWO_Trace/src/itm_trace.c \
02_Middleware_Platform/EasyLogger/port/elog_port.c \
02_Middleware_Platform/EasyLogger/src/elog.c \
02_Middleware_Platform/EasyLogger/src/elog_async.c \
02_Middleware_Platform/EasyLogger/src/elog_buf.c \
02_Middleware_Platform/EasyLogger/src/elog_utils.c \
02_Middleware_Platform/LetterShell/src/log.c \
02_Middleware_Platform/LetterShell/src/shell_cmd_list.c \
02_Middleware_Platform/LetterShell/src/shell_companion.c \
02_Middleware_Platform/LetterShell/src/shell_ext.c \
02_Middleware_Platform/LetterShell/src/shell_port.c \
02_Middleware_Platform/LetterShell/src/shell.c \
02_BSP_Platform/Bsp_Drivers/wt588f02/handler/src/linklist.c \
02_MCU_Platform/MCU_Core_IIC/i2c_port/src/i2c_port.c \
02_BSP_Platform/Bsp_Drivers/aht21/driver/src/bsp_aht21_driver.c \
02_BSP_Platform/Bsp_Drivers/aht21/handler/src/bsp_temp_humi_xxx_handler.c \
02_BSP_Platform/Bsp_Drivers/mpu6050/driver/src/bsp_mpuxxxx_driver.c \
02_BSP_Platform/Bsp_Drivers/mpu6050/driver/src/circular_buffer.c \
02_BSP_Platform/Bsp_Drivers/mpu6050/handler/src/bsp_mpuxxxx_handler.c \
02_BSP_Platform/Bsp_Drivers/wt588f02/driver/src/bsp_wt588_driver.c \
02_BSP_Platform/Bsp_Drivers/wt588f02/driver/src/bsp_wt588_hal_port.c \
02_BSP_Platform/Bsp_Drivers/wt588f02/handler/src/bsp_wt588_handler.c \
02_BSP_Platform/Bsp_Drivers/st7789/driver/src/bsp_st7789_driver.c \
02_BSP_Platform/Bsp_Drivers/st7789/driver/src/fonts.c \
02_BSP_Platform/Platform_Interface/temp_humi/bsp_wrapper_temp_humi/src/bsp_wrapper_temp_humi.c \
02_BSP_Platform/Platform_Interface/temp_humi/bsp_adapter_port_temp_humi/src/bsp_adapter_port_temp_humi.c \
02_BSP_Platform/Platform_Interface/motion/bsp_wrapper_motion/src/bsp_wrapper_motion.c \
02_BSP_Platform/Platform_Interface/motion/bsp_adapter_port_motion/src/bsp_adapter_port_motion.c \
02_BSP_Platform/Platform_Interface/audio/bsp_wrapper_audio/src/bsp_wrapper_audio.c \
02_BSP_Platform/Platform_Interface/audio/bsp_adapter_port_audio/src/bsp_adapter_port_audio.c \
01_APP/User_Init/Platform_IO_Register/src/platform_io_register.c \
02_BSP_Platform/Bsp_Integration/mpu6050_integration/src/mpu6050_integration.c \
02_BSP_Platform/Bsp_Integration/aht21_integration/src/aht21_integration.c \
02_BSP_Platform/Bsp_Integration/wt588_integration/src/wt588_integration.c \
01_APP/User_Init/user_init.c \
01_APP/User_Task_Config/src/user_task_reso_config.c \
01_APP/User_Task_Config/src/task_higher_water_monitor.c \
01_APP/User_Isr_handlers/src/user_isr_handlers.c \
01_APP/User_Sensor/mpu6050/src/mpu6050_unpack.c \
01_APP/User_Sensor/temp_humi/src/temp_humi_concurrency_test.c \
01_APP/User_Sensor/audio/src/wt588_test_task.c \
01_APP/User_Sensor/display/src/st7789_mock_test_task.c \
01_APP/User_Sensor/display/src/st7789_hal_test_task.c

# ASM sources
ASM_SOURCES =  \
startup_stm32f411xe.s

# ASM sources (uppercase .S, preprocessed)
ASM_SOURCES_S =  \
04_Debug_Tool/Systemview/inc/SEGGER_RTT_ASM_ARMv7M.S


#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
NM = $(GCC_PATH)/$(PREFIX)nm
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
NM = $(PREFIX)nm
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S

#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m4

# fpu
FPU = -mfpu=fpv4-sp-d16

# float-abi
FLOAT-ABI = -mfloat-abi=hard

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS =

# C defines
C_DEFS =  \
-DUSE_HAL_DRIVER \
-DSTM32F411xE


#######################################
# include paths
#######################################

# 02_OS_Platform — OSAL
C_INCLUDES_OSAL = \
-I02_OS_Platform/OSAL_Common/inc \
-I02_OS_Platform/OS_Implementation/inc \
-I02_OS_Platform/OS_Wrapper/inc

# 02_MCU_Platform
C_INCLUDES_MCU = \
-I02_MCU_Platform/MCU_Core_IIC/i2c_port/inc

# 02_Middleware_Platform
C_INCLUDES_MW = \
-I02_Middleware_Platform/EasyLogger/inc \
-I02_Middleware_Platform/LetterShell/inc

# 02_BSP_Platform
C_INCLUDES_BSP_DRV = \
-I02_BSP_Platform/Bsp_Drivers/aht21/driver/inc \
-I02_BSP_Platform/Bsp_Drivers/aht21/handler/inc \
-I02_BSP_Platform/Bsp_Drivers/mpu6050/driver/inc \
-I02_BSP_Platform/Bsp_Drivers/mpu6050/handler/inc \
-I02_BSP_Platform/Bsp_Drivers/wt588f02/driver/inc \
-I02_BSP_Platform/Bsp_Drivers/wt588f02/handler/inc \
-I02_BSP_Platform/Bsp_Drivers/st7789/driver/inc \

# 02_BSP_Platform — (wrapper + adapter)
C_INCLUDES_BSP_IF = \
-I02_BSP_Platform/Platform_Interface/temp_humi/bsp_wrapper_temp_humi/inc \
-I02_BSP_Platform/Platform_Interface/temp_humi/bsp_adapter_port_temp_humi/inc \
-I02_BSP_Platform/Platform_Interface/motion/bsp_wrapper_motion/inc \
-I02_BSP_Platform/Platform_Interface/motion/bsp_adapter_port_motion/inc \
-I02_BSP_Platform/Platform_Interface/audio/bsp_wrapper_audio/inc \
-I02_BSP_Platform/Platform_Interface/audio/bsp_adapter_port_audio/inc

# 02_BSP_Platform
C_INCLUDES_BSP_INT = \
-I02_BSP_Platform/Bsp_Integration/aht21_integration/inc \
-I02_BSP_Platform/Bsp_Integration/mpu6050_integration/inc \
-I02_BSP_Platform/Bsp_Integration/wt588_integration/inc

# 04_Debug_Tool
C_INCLUDES_DBG = \
-I04_Debug_Tool/Systemview/inc \
-I04_Debug_Tool/Debug_Log/inc \
-I04_Debug_Tool/SWO_Trace/inc \
-I04_Debug_Tool/MPU_Protect/inc

# 01_APP
C_INCLUDES_APP = \
-I01_APP/User_Init \
-I01_APP/User_Init/Platform_IO_Register/inc \
-I01_APP/User_Task_Config/inc \
-I01_APP/User_Sensor/mpu6050/inc

C_INCLUDES = \
-ICore/Inc \
-IDrivers/STM32F4xx_HAL_Driver/Inc \
-IDrivers/STM32F4xx_HAL_Driver/Inc/Legacy \
-IMiddlewares/Third_Party/FreeRTOS/Source/include \
-IMiddlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 \
-IMiddlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F \
-IDrivers/CMSIS/Device/ST/STM32F4xx/Include \
-IDrivers/CMSIS/Include \
$(C_INCLUDES_OSAL) \
$(C_INCLUDES_MCU) \
$(C_INCLUDES_MW) \
$(C_INCLUDES_BSP_DRV) \
$(C_INCLUDES_BSP_IF) \
$(C_INCLUDES_BSP_INT) \
$(C_INCLUDES_DBG) \
$(C_INCLUDES_APP) \


# AS includes
AS_INCLUDES =

CFLAGS = $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif

# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"

ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = STM32F411XX_FLASH.ld

# MCU memory size (STM32F411xE)
FLASH_SIZE_BYTES = 524288
RAM_SIZE_BYTES = 131072

# libraries
LIBS = -lc -lm -lnosys
LIBDIR =
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections -u _printf_float

# default action: build all
all: | $(BUILD_DIR)
ifeq ($(OS),Windows_NT)
	@powershell -NoProfile -ExecutionPolicy Bypass -File "./Tools/build_summary.ps1" -MakeExe "$(MAKE)" -BuildDir "$(BUILD_DIR)" -BuildLog "$(BUILD_LOG)" -Target "build-core"
else
	@start=$$(date +%s); \
	$(MAKE) --no-print-directory build-core > "$(BUILD_LOG)" 2>&1; \
	status=$$?; \
	cat "$(BUILD_LOG)"; \
	end=$$(date +%s); \
	elapsed=$$((end - start)); \
	warn_count=$$(grep -Eci '(^|[^[:alnum:]_])warning:' "$(BUILD_LOG)" || true); \
	err_count=$$(grep -Eci '(^|[^[:alnum:]_])error:' "$(BUILD_LOG)" || true); \
	echo; \
	echo "=== Build Summary ==="; \
	printf "Compile time: %02d:%02d (%ds)\n" $$((elapsed / 60)) $$((elapsed % 60)) $$elapsed; \
	echo "Warnings: $$warn_count"; \
	echo "Errors  : $$err_count"; \
	exit $$status
endif

build-core: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin mem-report


#######################################
# build the application
#######################################
OBJECTS  = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))

OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES_S:.S=.o)))
vpath %.S $(sort $(dir $(ASM_SOURCES_S)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR)
	$(CC) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(ASFLAGS) $< -o $@

$(BUILD_DIR)/%.o: %.S Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@

$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@

$(BUILD_DIR):
	mkdir $@

#######################################
# memory report
#######################################
ifeq ($(OS),Windows_NT)
mem-report: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin
	@powershell -NoProfile -ExecutionPolicy Bypass -File "./Tools/mem_report.ps1" -ElfPath "$(BUILD_DIR)/$(TARGET).elf" -LdPath "$(LDSCRIPT)" -SizeTool "$(SZ)"
else
mem-report: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin
	@echo "=== Memory Usage Summary ==="
	@flash=`$(SZ) $(BUILD_DIR)/$(TARGET).elf | awk 'NR==2 {print $$1 + $$2}'`; \
	ram=`$(SZ) $(BUILD_DIR)/$(TARGET).elf | awk 'NR==2 {print $$2 + $$3}'`; \
	flash_pct=`awk 'BEGIN {printf "%.2f", ('$$flash' * 100.0) / $(FLASH_SIZE_BYTES)}'`; \
	ram_pct=`awk 'BEGIN {printf "%.2f", ('$$ram' * 100.0) / $(RAM_SIZE_BYTES)}'`; \
	echo "FLASH used: $$flash / $(FLASH_SIZE_BYTES) bytes ($$flash_pct%)"; \
	echo "RAM used  : $$ram / $(RAM_SIZE_BYTES) bytes ($$ram_pct%)"
	@echo
	@echo "=== Section Breakdown ==="
	@$(SZ) -A $(BUILD_DIR)/$(TARGET).elf
	@echo
	@echo "=== Top 20 Symbols By Size ==="
	@$(NM) -S --size-sort $(BUILD_DIR)/$(TARGET).elf | tail -n 20
endif

#######################################
# clean up
#######################################
clean:
	-$(RM_DIR)

.PHONY: all build-core clean mem-report

#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***
