/******************************************************************************
 * @file rtconfig.h
 *
 * @brief RT-Thread kernel configuration for the STM32F411 APP firmware.
 *
 * @note Hand-written for this project, NOT generated by RT-Thread Studio /
 *       menuconfig. Values are chosen to mirror Core/Inc/FreeRTOSConfig.h so
 *       that the two backends behave the same; see the table below.
 *
 *       Everything RT-Thread offers beyond the kernel is deliberately off:
 *       no device framework, no finsh/msh, no POSIX/libc layer, no
 *       components-init. This project has its own BSP五段式, LetterShell and
 *       startup path, and pulling RT-Thread's equivalents in would duplicate
 *       them. That is also why drivers/ and components/ are not vendored.
 *
 * @note 1 tab == 4 spaces!
 *
 *****************************************************************************/

#ifndef RT_CONFIG_H__
#define RT_CONFIG_H__

/* ---------------------------------------------------------------- kernel -- */

/* Mirrors configMAX_TASK_NAME_LEN (16). Longest task name in
 * g_user_task_cfg[] is 24 chars, so both backends truncate identically. */
#define RT_NAME_MAX                     16

/* 8-byte alignment, required by AAPCS once the hard-float ABI is in play.
 * cpuport.c:25 auto-detects this build as an FPU target (__VFP_FP__ set,
 * __SOFTFP__ unset) and sets USE_FPU=1, so s16-s31 are saved across context
 * switches and rt_hw_stack_init() lays down the FPU stack frame. */
#define RT_ALIGN_SIZE                   8

/* Priority scale, kept aligned with the FreeRTOS backend: OSAL_PRIORITY_MAX
 * is 56 on both, so PRI_* resolve to identical numbers and the two builds can
 * be compared directly.
 *
 * RT-Thread only supports 8 / 32 / 256 levels -- scheduler.c hardcodes
 * rt_thread_ready_table[32] on the >32 path, which is an 8x32 = 256 bitmap.
 * 56 is therefore not representable and 256 is the smallest档 that holds it.
 * Cost over a 32-level table: rt_thread_priority_table[] 2048 B + ready_table
 * 32 B, i.e. ~1824 B more RAM.
 *
 * OSAL keeps the FreeRTOS convention (larger = higher); os_impl_task.c
 * inverts it as rt_prio = (OSAL_PRIORITY_MAX - 1) - osal_prio:
 *
 *   OSAL / FreeRTOS                RT-Thread
 *   PRI_EMERGENCY      55   -->     0
 *   PRI_HARD_REALTIME  51   -->     4
 *   PRI_SOFT_REALTIME  46   -->     9
 *   PRI_NORMAL         39   -->    16
 *   PRI_BACKGROUND      1   -->    54
 *   (idle)                  -->   255
 */
#define RT_THREAD_PRIORITY_256
#define RT_THREAD_PRIORITY_MAX          256

/* Mirrors configTICK_RATE_HZ (1000). */
#define RT_TICK_PER_SECOND              1000

/* Mirrors configCHECK_FOR_STACK_OVERFLOW (2). */
#define RT_USING_OVERFLOW_CHECK

/* Kernel hooks. Required by the SystemView RT-Thread integration
 * (SEGGER_SYSVIEW_RTThread.c hooks scheduler/object/malloc). */
#define RT_USING_HOOK
#define RT_USING_IDLE_HOOK
#define RT_IDLE_HOOK_LIST_SIZE          4
#define IDLE_THREAD_STACK_SIZE          256

/* Assertions during bring-up. */
#define RT_DEBUG

/* ------------------------------------------------------------ soft timer -- */

/* RT_TIMER_THREAD_PRIO is in RT-Thread's own scale (0 = highest). 53 is the
 * image of OSAL priority 2, i.e. configTIMER_TASK_PRIORITY, which sits one
 * notch above PRI_BACKGROUND (1 -> 54) and below everything else.
 * Stack is bytes here; configTIMER_TASK_STACK_DEPTH is 256 words = 1024 B. */
#define RT_USING_TIMER_SOFT
#define RT_TIMER_THREAD_PRIO            53
#define RT_TIMER_THREAD_STACK_SIZE      1024

/* -------------------------------------------------------------- IPC ------ */

#define RT_USING_SEMAPHORE
#define RT_USING_MUTEX
#define RT_USING_EVENT
#define RT_USING_MAILBOX
#define RT_USING_MESSAGEQUEUE

/* -------------------------------------------------------------- memory --- */

#define RT_USING_HEAP
#define RT_USING_SMALL_MEM

/* ------------------------------------------------------------- console --- */

/* rt_kprintf() routes to rt_hw_console_output(), implemented by this project
 * on top of DEBUG_OUT. No rt_device is involved (RT_USING_DEVICE is off). */
#define RT_USING_CONSOLE
#define RT_CONSOLEBUF_SIZE              128

/* ---------------------------------------------------------------- arch --- */

#define ARCH_ARM
#define ARCH_ARM_CORTEX_M
#define ARCH_ARM_CORTEX_M4
#define RT_USING_CPU_FFS

#define RT_VER_NUM                      0x40003

#endif /* RT_CONFIG_H__ */
